name: Run Linter to validate the code style

on: [pull_request, push]

jobs:
  lint-styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint
